name: notebook-nglview
dependencies:
- python=3.6
- nglview=1.0
- ipywidgets==7.0.0
- ipykernel=4.6
- ambertools=17
- mdtraj
- mdanalysis

channels:
  - anaconda
  - bioconda
  - http://ambermd.org/downloads/ambertools/conda/
  - conda-forge
  - kain88-de
  - MDAnalysis
  - omnia
