name: notebook-nglview
dependencies:
- python=3.6
- matplotlib
- nglview=1.0
- ipywidgets==7.0.0
- ipykernel=4.6
- pytraj=2.0
- mdtraj
- mdanalysis

channels:
  - anaconda
  - bioconda
  - conda-forge
  - ambermd
  - kain88-de
  - MDAnalysis
  - omnia
