name: notebook-nglview
dependencies:
- python=3.6
- matplotlib
- nglview=1.0
- pytraj
- mdtraj
- mdanalysis

channels:
  - anaconda
  - conda-forge
  - bioconda
  - ambermd
  - kain88-de
  - MDAnalysis
  - omnia
