name: notebook-nglview
dependencies:
- python=3.5
- matplotlib
- nglview=0.5
- pytraj
- mdtraj
- mdanalysis
- traitlets=4.2.1
- ipywidgets==4.1.1
- notebook=4.1.0

channels:
  - anaconda
  - ambermd
  - kain88-de
  - MDAnalysis
  - omnia
